[tool.poetry]
name = "nephelaiio-ubuntu-installer"
version = "6.2.5"
description = ""
authors = ["Ted Cook <teodoro.cook@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
boto = "^2.49.0"
boto3 = "^1.28.10"
ansible = "^8.2.0"
netaddr = "^0.8.0"
molecule = {extras = ["ec2"], version = "^5.1.0"}
ansible-lint = { version = "*", markers = "platform_system != 'Windows'" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
