---
- name: Destroy KVM guests

  hosts: localhost

  become: true

  tasks:

    - name: Destroy KVM guest
      community.libvirt.virt:
        state: destroyed
        name: "{{ guest.installer_hostname }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      failed_when: false

    - name: Undefine KVM guest
      community.libvirt.virt:
        command: undefine
        name: "{{ guest.installer_hostname }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      failed_when: false

    - name: Destroy KVM guest disks
      ansible.builtin.file:
        path: "{{ guest_disk }}"
        state: absent
      vars:
        guest_disk: "{{ cache_dir }}/{{ guest.installer_hostname }}.img"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"

    - name: Destroy dummy bridge
      ansible.builtin.command: "nmcli con del {{ bridge_name }}"
      failed_when: false

    - name: Destroy dummy interface
      ansible.builtin.command: "ip link del {{ bridge_iface }}"
      failed_when: false

    - name: Destroy dummy bridge
      ansible.builtin.command: "ip link del {{ bridge_name }} type bridge"
      failed_when: false
