---
- name: Destroy KVM resources
  ansible.builtin.import_playbook: nephelaiio.libvirt.destroy

- name: Destroy KVM disks
  hosts: all
  connection: local
  gather_facts: false
  become: "{{ lookup('ansible.builtin.env', 'CI') | default('false') | bool }}"
  tasks:
    - name: Destroy KVM guest disks
      ansible.builtin.file:
        path: "{{ libvirt_path }}/{{ inventory_hostname }}.add.img"
        state: absent
      delegate_to: localhost
