---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: installer
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      host_key_checking: false
  inventory:
    hosts:
      all:
        vars:
          molecule_distro: "{{ lookup('env', 'MOLECULE_DISTRO', default='focal') }}"
          molecule_iso: "{{ lookup('env', 'MOLECULE_ISO', default='https://releases.ubuntu.com/focal/ubuntu-20.04.6-live-server-amd64.iso') }}"
          cache_dir: "/tmp/{{ molecule_distro }}"

          bridge_net: "{{ '192.168.255.0/24' | ipv4('network/prefix') }}"
          bridge_host: "{{ bridge_net | nthhost(1) }}"
          bridge_prefix: "{{ bridge_net | ipaddr('prefix') }}"
          bridge_name: "{{ molecule_distro }}br0"
          bridge_iface: "{{ molecule_distro }}0"

          kvm_keypair: "{{ cache_dir }}/kvm_key"

          iso_installer:
            dest: "file://{{ cache_dir }}/server-live.iso"
            url: "{{ molecule_iso }}"

          guests:

            - installer_hostname: "{{ molecule_distro }}-lvm-10g"
              installer_image_url: "{{ iso_installer.url }}"
              installer_disk_size: "{{ 10*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ bridge_net | nthhost(2) }}"
                network: "{{ bridge_net | ipaddr('network') }}"
                netmask: "{{ bridge_net | ipaddr('netmask') }}"
                gateway: "{{ bridge_host }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: lvm

            - installer_hostname: "{{ molecule_distro }}-static-10g"
              installer_image_url: "{{ iso_installer.url }}"
              installer_disk_size: "{{ 10*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ bridge_net | nthhost(3) }}"
                network: "{{ bridge_net | ipaddr('network') }}"
                netmask: "{{ bridge_net | ipaddr('netmask') }}"
                gateway: "{{ bridge_host }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: regular

            - installer_hostname: "{{ molecule_distro }}-lvm-50g"
              installer_image_url: "{{ iso_installer.url }}"
              installer_disk_size: "{{ 50*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ bridge_net | nthhost(4) }}"
                network: "{{ bridge_net | ipaddr('network') }}"
                netmask: "{{ bridge_net | ipaddr('netmask') }}"
                gateway: "{{ bridge_host }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: lvm

            - installer_hostname: "{{ molecule_distro }}-static-50g"
              installer_image_url: "{{ iso_installer.url }}"
              installer_disk_size: "{{ 50*(1024**3) }}"
              installer_interface:
                static: true
                ipaddress: "{{ bridge_net | nthhost(5) }}"
                network: "{{ bridge_net | ipaddr('network') }}"
                netmask: "{{ bridge_net | ipaddr('netmask') }}"
                gateway: "{{ bridge_host }}"
                nameservers:
                  - 1.1.1.1
                  - 8.8.8.8
              installer_partitioning_method: regular

verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
