---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: "${MOLECULE_SCENARIO_NAME}-lvm-10g"
  - name: "${MOLECULE_SCENARIO_NAME}-static-10g"
  - name: "${MOLECULE_SCENARIO_NAME}-lvm-50g"
  - name: "${MOLECULE_SCENARIO_NAME}-static-50g"
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_VERBOSITY:-0}
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    group_vars:
      all:
        ubuntu_installer_target_dir: "{{ libvirt_path }}"
        ubuntu_installer_dest: "{{ libvirt_path }}/server-live.iso"
        ubuntu_installer_url: "{{ molecule_installer_url }}"

        libvirt_network: "nephelaiio-growfs"
        libvirt_platforms: "{{ molecule_yml.platforms }}"
        libvirt_address: "172.31.249.1/24"
        libvirt_path: "{{ molecule_project }}/libvirt/nephelaiio-ubuntu-installer"
        libvirt_privkey: "{{ libvirt_path }}/id_rsa"
        libvirt_guest_iso: "{{ libvirt_path }}/{{ inventory_hostname }}.iso"
        libvirt_nameservers:
          - 1.1.1.1
          - 8.8.8.8

        molecule_distro: "{{ lookup('env', 'MOLECULE_DISTRO') }}"
        molecule_installer_url: "{{ lookup('env', 'MOLECULE_ISO') }}"
        molecule_install_dir: "{{ lookup('env', 'MOLECULE_OUTPUT_DIR', default='/tmp/logs') }}"
        molecule_network: "{{ libvirt_address | ansible.utils.ipaddr('network') }}"
        molecule_netmask: "{{ libvirt_address | ansible.utils.ipaddr('netmask') }}"
        molecule_prefix: "{{ libvirt_address | ansible.utils.ipaddr('prefix') }}"
        molecule_netaddr: "{{ molecule_network }}/{{ molecule_prefix }}"
        molecule_project: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"

    host_vars:
      localhost:
        ansible_connection: local
        ansible_python_interpreter: python

      ${MOLECULE_SCENARIO_NAME}-lvm-10g:
        libvirt_guest_size: "{{ 10*(1024**3) }}"
        libvirt_guest_address: "{{ molecule_netaddr | ansible.utils.nthhost(2) }}"
        partitioning_method: lvm
        installer_interface:
          static: true
          ipaddress: "{{ libvirt_guest_address }}"
          network: "{{ molecule_network }}"
          netmask: "{{ molecule_netmask }}"
          gateway: "{{ libvirt_address | ansible.utils.ipaddr('address') }}"
          nameservers: "{{ libvirt_nameservers }}"

      ${MOLECULE_SCENARIO_NAME}-static-10g:
        libvirt_guest_size: "{{ 10*(1024**3) }}"
        libvirt_guest_address: "{{ molecule_netaddr | ansible.utils.nthhost(3) }}"
        partitioning_method: regular
        installer_interface:
          static: true
          ipaddress: "{{ libvirt_guest_address }}"
          network: "{{ molecule_network }}"
          netmask: "{{ molecule_netmask }}"
          gateway: "{{ libvirt_address | ansible.utils.ipaddr('address') }}"
          nameservers: "{{ libvirt_nameservers }}"

      ${MOLECULE_SCENARIO_NAME}-lvm-50g:
        libvirt_guest_size: "{{ 50*(1024**3) }}"
        libvirt_guest_address: "{{ molecule_netaddr | ansible.utils.nthhost(4) }}"
        partitioning_method: lvm
        installer_interface:
          static: true
          ipaddress: "{{ libvirt_guest_address }}"
          network: "{{ molecule_network }}"
          netmask: "{{ molecule_netmask }}"
          gateway: "{{ libvirt_address | ansible.utils.ipaddr('address') }}"
          nameservers: "{{ libvirt_nameservers }}"

      ${MOLECULE_SCENARIO_NAME}-static-50g:
        libvirt_guest_size: "{{ 50*(1024**3) }}"
        libvirt_guest_address: "{{ molecule_netaddr | ansible.utils.nthhost(5) }}"
        partitioning_method: regular
        installer_interface:
          static: true
          ipaddress: "{{ libvirt_guest_address }}"
          network: "{{ molecule_network }}"
          netmask: "{{ molecule_netmask }}"
          gateway: "{{ libvirt_address | ansible.utils.ipaddr('address') }}"
          nameservers: "{{ libvirt_nameservers }}"

verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - prepare
    - create
    - converge
    - verify
    - cleanup
