---
- name: Prepare KVM host
  ansible.builtin.import_playbook: nephelaiio.libvirt.prepare

- name: Prepare KVM assets
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure libvirt path exists
      ansible.builtin.file:
        dest: "{{ libvirt_path }}"
        state: directory
        mode: "u=rwx,go=rx"

    - name: Create KVM keypair
      ansible.builtin.command:
        cmd: "ssh-keygen -t rsa -f {{ libvirt_privkey }} -q -P '' -C ''"
        creates: "{{ libvirt_privkey }}"

    - name: Cache installer iso
      ansible.builtin.get_url:
        url: "{{ molecule_installer_url }}"
        dest: "{{ libvirt_path }}/{{ molecule_distro }}.iso"
