---
name: Lint

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * 0"

defaults:
  run:
    working-directory: 'nephelaiio.ubuntu_installer'

jobs:
  lint:
    name: lint
    runs-on: libvirt
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'nephelaiio.ubuntu_installer'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install poetry
        run: pip install poetry

      - name: Install test dependencies.
        run: poetry install

      - name: Lint code with ansible-lint
        run: poetry run ansible-lint .

      - name: Lint code with yamllint
        run: poetry run yamllint .

      - name: Lint code with molecule
        run: poetry run molecule syntax
