---
name: Lint

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: 'nephelaiio.ubuntu_installer'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: 'nephelaiio.ubuntu_installer'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Lint code
        run: make lint
