---
name: molecule
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  SCENARIO: default
  LOGDIR: /tmp/logs
jobs:
  libvirt:
    name: libvirt
    runs-on: libvirt
    strategy:
      matrix:
        partition_size:
          - 10
          - 50
        distro:
          - jammy
          - focal
          - noble
        partition_method:
          - lvm
          - regular
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: |
            make requirements test \
              MOLECULE_SCENARIO=${{ env.SCENARIO }} \
              MOLECULE_LOGDIR=${{ env.LOGDIR }} \
              MOLECULE_KVM_IMAGE=${{ matrix.image }} \
              MOLECULE_PARTITION_METHOD=${{ matrix.partition_method }} \
              MOLECULE_PARTITION_SIZE=${{ matrix.partition_size }}

      - name: Upload install logs
        uses: actions/upload-artifact@v6
        with:
          name: install.${{ env.SCENARIO }}.${{ matrix.distro }}
          path: |
            ${{ env.LOGDIR }}/*.log
            ${{ env.LOGDIR }}/*.ppm
          if-no-files-found: ignore
        if: always()
